// <auto-generated />
using JWTTeste.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JWTTeste.Migrations
{
    [DbContext(typeof(JWTTesteDbContext))]
    [Migration("20211004194359_UpdatePasswordSize")]
    partial class UpdatePasswordSize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JWTTeste.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_USUARIO")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("VARCHAR(60)")
                        .HasColumnName("CD_EMAIL");

                    b.Property<string>("Nome")
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("NM_USUARIO");

                    b.Property<string>("Perfil")
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("CD_PERFIL");

                    b.Property<string>("Senha")
                        .HasColumnType("VARCHAR(60)")
                        .HasColumnName("CD_SENHA");

                    b.HasKey("Id");

                    b.ToTable("TB_USUARIO");
                });
#pragma warning restore 612, 618
        }
    }
}
